

<meta name="viewport" content="width=device-width, maximum-scale=1, user-scalable=no">
<link rel="stylesheet" href="css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
<!--<link rel="stylesheet" href="css/bootstrap-theme.min.css">->I dont know how but this negatively affects the xy page-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-bootgrid/1.3.1/jquery.bootgrid.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-bootgrid/1.3.1/jquery.bootgrid.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
<link rel="stylesheet" href="css/style.css">
<link rel="stylesheet" href="css/login.css">
<script src='js/Functions/Link.js'></script>
<link rel="stylesheet" href="css/datapages.css"/>
<script src='js/Functions/datapagexy.js'></script>
<script src='js/Functions/ChartValidator.js'></script>
<link href="css/bootstrap-responsive.css" rel="stylesheet">
<link rel="icon" href='Logo/TruiiLogoIcon.png'>
<link rel="stylesheet" type="text/css" href="css/spectrum.css">
<script src="js/spectrum.js"></script>
